spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: haozhuqian801219
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:/mapper/*.xml
file-save-path: ..\static\image
